apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-examplecom
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - keycloak.example.com
    secretName: tls-com-example-keycloak
  rules:
  - host: keycloak.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-external
          servicePort: 8080
      - path: /auth
        backend:
          serviceName: keycloak-external
          servicePort: 8080
